[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[functions.starling-sync]
  schedule = "0 6 * * *"

[functions.stripe-sync]
  schedule = "0 6 * * *"
